buildspec-release.yml
- discard build output path for artifact so that build deploy can find the file package
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> fix: discard build output artifact path

setup.py, src/sagemaker_inference/model_server.py, test/unit/test_model_server.py
DO NOT MERGE. Still want to do some more testing after PyTorch 1.2 is released first.
User running into memory issues due to tail. See for more information: https://github.com/aws/sagemaker-inference-toolkit/issues/9
User ran into an error due to the command "tail -f /dev/null".
The tail call is meant to keep the container running, instead I now wait on the server process to finish or return an error code. The reason why the process that is responsible for starting the mxnet-model-server can't be used to wait is because [MMS starts another subprocess](https://github.com/awslabs/mxnet-model-server/blob/master/mms/model_server.py#L136), which for some reason can't be tracked by calling `children()` on the mms_process. When looking at the …
=> fix: wait for mms server process to finish instead of tailing dev null

src/sagemaker_inference/model_server.py, test/unit/test_model_server.py
DO NOT MERGE. Want to do additional testing after the PyTorch 1.2 release.
https://github.com/aws/sagemaker-inference-toolkit/issues/9
https://github.com/aws/sagemaker-python-sdk/issues/957
https://github.com/aws/sagemaker-python-sdk/issues/664
Added code to support installing requirements.txt.
This makes the assumption that the requirements.txt will be in the /opt/ml/model/code/ as defined in the [environments.py](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/environment.py#L32) and in the [tensorflow-serving-container](https://github.com/aws/sagemaker-tensorflow-serving-container/blob/master/container/sagemaker/serve.py#L32).
The unit tests are very bare... I was able to patch …
=> feature: support requirements.txt

.github/ISSUE_TEMPLATE/config.yml, .github/PULL_REQUEST_TEMPLATE.md
- Adds a template for pull requests
- Adds `config.yml`, which [configures the issue template chooser](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository#configuring-the-template-chooser) so that issue templates (added in #30) can be selected
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> documentation: Add pull request template and issue template config

.github/ISSUE_TEMPLATE/bug_report.md, .github/ISSUE_TEMPLATE/documentation-request.md, .github/ISSUE_TEMPLATE/feature_request.md
- Adds [issue templates](https://help.github.com/en/github/building-a-strong-community/configuring-issue-templates-for-your-repository) to be available for selection from the template chooser.
By submitting this pull request, I confirm that you can use, modify, copy, and redistribute this contribution, under the terms of your choice.
=> documentation: Add issue templates

.coveragerc_py37, buildspec-release.yml, buildspec.yml, setup.py, tox.ini
- Update buildspecs to test against `py37`
- Update Python version in `setup.py`
- Update tox `envlist`
Ran unit tests locally and testing with the PR build system.
=> feature: Add Python 3.7 support

buildspec-release.yml, buildspec.yml
Parallelizing unit tests in builds seems to cause flakiness. (Noticed this in the release pipeline.) Removing parallelization.
Testing with PR build and release pipeline.
=> infra: Do not parallelize unit tests in buildspecs

setup.py, src/sagemaker_inference/decoder.py, src/sagemaker_inference/encoder.py
https://github.com/aws/sagemaker-training-toolkit/issues/60
- There is a known conflict between the built-in `typing` package in Python 3.7 and the backported `typing` package available through PyPI.
- Since this toolkit supports both Python 2.7 and 3.7, the `typing` PyPI dependency and all usage of `typing` have been removed.
Ran tox locally.
=> fix: Remove typing

src/sagemaker_inference/transformer.py, test/container/dummy/mme_handler_service.py, test/unit/test_transfomer.py
#50
When handling an inference error, we don't include the stacktrace in the response (see #50)
* unit tests
* built the MXNet image and ran a local endpoint with an inference script designed to fail
=> fix: include stacktrace when handling an error

README.md
The package exists under the name 'sagemaker-inference'. This change fixes the name for the pip install command from nonexistant 'sagemaker-inference-toolkit'
None
Changed the name of package to 'sagemaker-inference' in the pip install command in README.md
None, documentation change 
=> documentation: fix package name in pip install command

src/sagemaker_inference/default_inference_handler.py, src/sagemaker_inference/encoder.py, src/sagemaker_inference/utils.py, test/unit/test_default_inference_handler.py, test/unit/test_utils.py
* Add support for Accept headers with multiple MIME types
* Added a test to test_utils, and updated a test in test_default_inference_handler
=> feature: Support multiple accept types

src/sagemaker_inference/transformer.py, src/sagemaker_inference/utils.py, test/unit/test_utils.py
When an inference error occurs, MMS logs the following message:
```
java.lang.IllegalArgumentException: reasonPhrase contains one of the following prohibited characters: \r\n:
```
The root cause of this issue is actually from Netty, which is a dependency of MMS:
- https://github.com/netty/netty/issues/8312
- https://github.com/netty/netty/blob/0cde4d9cb4d19ddc0ecafc5be7c5f7c781a1f6e9/codec-http/src/main/java/io/netty/handler/codec/http/HttpResponseStatus.java#L552
As a workaround, we remove the offending characters from the error message.
- Added a unit test.
- Manual testing with a PyTorch inference container deployed to an endpoint.
_Put an `x` in the boxes that apply. You can also fill these out after creating the PR. …
=> fix: remove prohibited characters from error response

src/sagemaker_inference/transformer.py
- https://github.com/aws/sagemaker-inference-toolkit/pull/62 fixed an issue with prohibited characters by removing them from the inference exception response. This fixed the error, but it caused the stack trace to be unreadable.
- After further testing, only the response phrase needed to be sanitized. This PR leaves the stack trace and message with new line characters to improve readability.
- Manual testing with a PyTorch inference container deployed to an endpoint.
By submitting this pull …
=> fix: clean up stack trace and sanitize only response phrase

src/sagemaker_inference/model_server.py
Fixing issue https://github.com/aws/sagemaker-inference-toolkit/issues/82
The change includes using the option `` as suggested in the [documentation](https://docs.aws.amazon.com/sagemaker/latest/dg/deploy-model-troubleshoot.html#deploy-model-troubleshoot-jvms) 
I have built a custom container using the patched version and the CPU count matches available CPU count in the container. 
=> fix: Fixing issue #82

buildspec-release.yml, buildspec.yml, src/sagemaker_inference/model_server.py, test/integration/local/test_dummy_multi_model.py, test/integration/local/test_mxnet_multi_model.py
Increased timeout for starting model server to 10 minutes. This is due to an issue under heavy CPU load that sometimes arises where it would not start up in time, in SageMaker Multi-Model Endpoint scenarios with large models.
Ran unit tests.
=> fix: Increase timeout for starting model server to 10 minutes

buildspec.yml
Revert the change to disable output capturing, done as part of this PR https://github.com/aws/sagemaker-inference-toolkit/pull/92 as it is not necessary.
=> fix: Re-enable output capturing

README.md, src/sagemaker_inference/default_handler_service.py, src/sagemaker_inference/default_inference_handler.py, src/sagemaker_inference/transformer.py, test/unit/test_default_inference_handler.py, test/unit/test_transfomer.py, tox.ini
MMS and TorchServe store request information in [context](https://github.com/awslabs/multi-model-server/blob/master/mms/context.py#L16) object and pass it to the [handler service](https://github.com/aws/sagemaker-inference-toolkit/blob/master/src/sagemaker_inference/default_handler_service.py#L52) function. This PR further pass the context to the handler function so that users can use those information in the custom handler function. 
One particular use case is multi-GPU inference for PyTorch and MXNet. Currently handler functions[ statically select](https://github.com/aws/sagemaker-pytorch-inference-toolkit/blob/master/src/sagemaker_pytorch_serving_container/default_pytorch_inference_handler.py#L121-123) the same GPU device and assign all data/model to that …
=> Pass context from handler service to handler function

src/sagemaker_inference/transformer.py, test/unit/test_transfomer.py
This PR fixes the issue described here in PT inference toolkit repo, since the fix can be applied at the transform function in the sagemaker inference toolkit, which PT toolkit inherits from.
1. This PR fixes the issue where the transform() function drops all but one requests when running prediction.
2. This PR adds a transform() function to override the transform() function from the sagemaker-inference-toolkit. It loops through the input data and runs _transform_fn() on each input. Then, it appends the response to a list. When all inputs are processed, the list is returned.
Config used:
```
env_variables_dict = {
"SAGEMAKER_TS_BATCH_SIZE": "3",
"SAGEMAKER_TS_MAX_BATCH_DELAY": "10000",
"SAGEMAKER_TS_MIN_WORKERS": "1", …
```
=> Modify transform function to support batch inference

setup.py, src/sagemaker_inference/model_server.py, test/unit/test_model_server.py
*Issue #, if available:* #85
- add a dependency on boto3 for calling codeartifact apis
- update model_server to check for the presence of codeartifact (CA_* prefixed) environment variable
- if env variable is present, build the authenticated endpoint index url, and add that to the pip install command
- unit tests
- container testing in https://github.com/aws/sagemaker-inference-toolkit/pull/130#issuecomment-1636911075
By submitting this pull request, I confirm that my contribution is made …
=> feat: support codeartifact for installing requirements.txt packages

setup.py, src/sagemaker_inference/model_server.py, test/integration/local/test_dummy_multi_model.py, test/integration/local/test_mxnet_multi_model.py
Due to upgrade of `psutil` version from `5.9.5` to `5.9.6`, customers started facing this error:
```
"Traceback (most recent call last):
File ""/usr/local/bin/dockerd-entrypoint.py"", line 21, in <module>
main()
File ""/usr/local/bin/dockerd-entrypoint.py"", line 13, in main
_start_model()
File ""/usr/local/bin/dockerd-entrypoint.py"", line 9, in _start_model
model_server.start_model_server(handler_service=""/home/model-server/model_files/model_handler.py:handle"")
File ""/home/model-server/venv/lib/python3.8/site-packages/sagemaker_inference/model_server.py"", line 102, in start_model_server
mms_process = _retry_retrieve_mms_server_process(env.startup_timeout)
File ""/home/model-server/venv/lib/python3.8/site-packages/sagemaker_inference/ …
```
=> Fix zombie process exception
